global:
    tracker_mqtt_settings:
        connection:
            host: ENC[AES256_GCM,data:riPvtH4XDQhQAVw8,iv:c1YL7WygyOhb8ARNFrZRQyQ6lV3PCwKXbImj6BMgbuY=,tag:RfjA0wiWxiVwHQ4t3qTIQQ==,type:str]
            port: ENC[AES256_GCM,data:JkUlhg==,iv:vXQDSNR9tHtyrO5Ldk1jyNIEpAIOrlMBtwpxiqfEuEs=,tag:RGjFYfkdp+zluj8K+wa/Bw==,type:int]
            client_id: ENC[AES256_GCM,data:L1CWqD6PamvxDhFf,iv:iNXJlckQwOVQ94jafZgvBIo9BzPD9BgAj38A+cff12Q=,tag:0TYZwtuZRgpU14Cw2bz/DA==,type:str]
garage_doors:
    - ENC[AES256_GCM,data:IA55AbRbR7Y9O81vwkZjDQYCx1SThTYKy9/CEZhGG+Jdz6n6nn/caCTVfjdvhBjBrP2tN0Qp5AEIUNofCEusJ+MzwozBnwPAOwEAMaE9RC1fwPStVmLboo+R+1BbzjEH12epnT+hD1/ZffqCqZjMNsiAq6S9tAzOClBjBdt0rg==,iv:WnWbdxXHRYcHdVT3KQ/Bq+DBjCw/ncEAbL1sg5DfqjU=,tag:oot3juwG4tOVp8/N2yOcnQ==,type:comment]
    - geofence:
        type: ENC[AES256_GCM,data:IXppmqSS3O0=,iv:ujQW3huD8nJfu48aLAs9p2eWNudsZpr9RHS48LbmjRs=,tag:7tOogxAT0Ykftrg7ig3wyA==,type:str]
        settings:
            center:
                lat: ENC[AES256_GCM,data:anzGKMG3z07b,iv:0xi0Eh42mrYYew0pVtYqEdnz1agP9WCVZko8hX0UwrU=,tag:TlpbPsZ1sK65qiLgKaxTJw==,type:float]
                lng: ENC[AES256_GCM,data:woUeLirOo4zl3g==,iv:psLF/xt9GwtJAwvp0KXVZEJbEOBa2852ISYWI6367iQ=,tag:rkfI5CIUzSlUqeZu4REZ3A==,type:float]
            #ENC[AES256_GCM,data:VGG7Wy89mj4fSOEQal7lHyOKcxE=,iv:JWMQ+btru6kKk+1LcWrnlsvbvuCgQRDQMeaqS+k0mUs=,tag:us/Ad2lbRAxL5W6z+8puPQ==,type:comment]
            open_distance: ENC[AES256_GCM,data:+BlwCA==,iv:Tx3OWj+i3ZObU0l13Eu6P6mVwdPTHWmITtQKP3QxlsM=,tag:l7sHHYIcW1Y/MS/E/PHf0g==,type:float]
      opener:
        type: ENC[AES256_GCM,data:Erx6qU0a6L/xgqa/Tw==,iv:e0a7kZNvsPSW4IKrq53YPj5fco1gSiImUX33pGAjeao=,tag:nyQwZ/qNGShc6pfNMZqqJw==,type:str]
        settings:
            connection:
                host: ENC[AES256_GCM,data:WjFxikUAvOmkvjk7bublomdtDpMTobnyUK8t,iv:um56irqROQvjjqRNZnhgUPWXaB/R0tYbYVfeEhmtc8w=,tag:tiF9yoUo2QOJh2XX/JErzg==,type:str]
                port: ENC[AES256_GCM,data:JipnXQ==,iv:YFnCyliKri3Ix+TdCI2Pa9qI9M+dQgyQQ6aWwnlcLe0=,tag:UQX+5WSChE1nBJARybyR6w==,type:int]
                api_key: ENC[AES256_GCM,data:CXfAfpdxL2gtXuxc74VC0NjjKr+QI0Xlt/N6GWthzhuUpSCMtm83nGEttyt/H0UtQTJnABhlVfL3825uwV9EDwwNEMtJtx0Te3m1dRsWUdmgs7+gwQsEhHJVN+d5jcXUK0UcKGc/LID5JQKUeGSGSe9XLoiKHh0xKXNYrEAeiXLPM3l1ZJioLvTqk1nYsSQr1x6CfpV/W3BhwaYuSrcuQJw0A0zWK/Zdy+FSElLCIf22bOJsGaa6,iv:2JZnSnUaqVqI76c7ryR2tCRUSsYq/u9hD5NwnqSGiIA=,tag:Laq1Ewp+yK/zHljsO1TJBQ==,type:str]
                use_tls: ENC[AES256_GCM,data:BuvAwkI=,iv:bhsIQm+hnveNmHg+vHglU77CzOy6I2aJhHSTw2PtpzA=,tag:7wUG9dQ0OgC+oqSoWICr0w==,type:bool]
            entity_id: ENC[AES256_GCM,data:tP1YYv3jFJP3pTb/26gPJ5sZL9zwn44=,iv:9hiWnVu2GMjly7CHqly1n3SkxwQf45MYsgARAlOAkoY=,tag:yYb8S3E/6qqfBZeDhntwKQ==,type:str]
            enable_status_checks: ENC[AES256_GCM,data:C7K0jw==,iv:JdUlANrh12vntrsLy2v6jug0LpswTNMXGCJxZvgWWpw=,tag:/ZOb9Z+zKgYmbre9kI38cw==,type:bool]
      trackers:
        - id: ENC[AES256_GCM,data:yg==,iv:TGJlkMqBFvIi+VlU7pF6rckwUl3FgTZVGdNzEEW9cgo=,tag:zlsMGaRtXvtIYCxUbPNdbw==,type:int]
          lat_topic: ENC[AES256_GCM,data:wY4qKdTnonOnAga2MgdOfumDTKy4Xes2UA==,iv:YBUP80DOs2uNpNHrWt+tilZSN9RSpNKNkqBag91Wy/s=,tag:QeNugGf0wpji9T4/qYOVxw==,type:str]
          lng_topic: ENC[AES256_GCM,data:bUlX5TEMfWPn8hpxgGPs0XC0h0RPwwyY2vI=,iv:oMRqZyS++flvUJhU9dzNsyRxifrriDjeduk/vsWvYhY=,tag:raVySbvmU4HiTumGKxlySQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/deft-epigram-262002/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2024-02-17T19:04:18Z"
          enc: CiQAXK0pKh+2bRdzg4qGtRwouk1ZpQtdJ2u/DVsGk76+vlOeLYISSQAZIbLB5J8G6sxljjL95Sji286qVUEo+SN4rO9SPtKazo2qObyA+YG7Szff7Ks8l5YcUfedCY77j3zediPNpY89JhsgpatejTQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-06T18:07:17Z"
    mac: ENC[AES256_GCM,data:Pc9aaE0yIAN+sqHdvFQ/i5d4K6mQGrC4DkgfJl1/O3SJadiandcgTmpVDd6A1VkJBk3OdDMGEXSF6ek9VmsJPW+lq+AZ4ZhYbQYjpZh7DzOJX3maJoxT+HDMjmd9Y8yeM0rabK6oMzmGl5GRhGkQ46DDUcH7Ya/kRWHPLSuvK44=,iv:4tsAIbN/aiRlwqK46CkwEmyN3kLpzWr69Q681mjBz0o=,tag:ZWoit9f4PAvI6JPmQgj+1Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
