global:
    tracker_mqtt_settings:
        connection:
            host: ENC[AES256_GCM,data:riPvtH4XDQhQAVw8,iv:c1YL7WygyOhb8ARNFrZRQyQ6lV3PCwKXbImj6BMgbuY=,tag:RfjA0wiWxiVwHQ4t3qTIQQ==,type:str]
            port: ENC[AES256_GCM,data:JkUlhg==,iv:vXQDSNR9tHtyrO5Ldk1jyNIEpAIOrlMBtwpxiqfEuEs=,tag:RGjFYfkdp+zluj8K+wa/Bw==,type:int]
            client_id: ENC[AES256_GCM,data:L1CWqD6PamvxDhFf,iv:iNXJlckQwOVQ94jafZgvBIo9BzPD9BgAj38A+cff12Q=,tag:0TYZwtuZRgpU14Cw2bz/DA==,type:str]
garage_doors:
    - ENC[AES256_GCM,data:IA55AbRbR7Y9O81vwkZjDQYCx1SThTYKy9/CEZhGG+Jdz6n6nn/caCTVfjdvhBjBrP2tN0Qp5AEIUNofCEusJ+MzwozBnwPAOwEAMaE9RC1fwPStVmLboo+R+1BbzjEH12epnT+hD1/ZffqCqZjMNsiAq6S9tAzOClBjBdt0rg==,iv:WnWbdxXHRYcHdVT3KQ/Bq+DBjCw/ncEAbL1sg5DfqjU=,tag:oot3juwG4tOVp8/N2yOcnQ==,type:comment]
    - geofence:
        type: ENC[AES256_GCM,data:IXppmqSS3O0=,iv:ujQW3huD8nJfu48aLAs9p2eWNudsZpr9RHS48LbmjRs=,tag:7tOogxAT0Ykftrg7ig3wyA==,type:str]
        settings:
            center:
                lat: ENC[AES256_GCM,data:anzGKMG3z07b,iv:0xi0Eh42mrYYew0pVtYqEdnz1agP9WCVZko8hX0UwrU=,tag:TlpbPsZ1sK65qiLgKaxTJw==,type:float]
                lng: ENC[AES256_GCM,data:woUeLirOo4zl3g==,iv:psLF/xt9GwtJAwvp0KXVZEJbEOBa2852ISYWI6367iQ=,tag:rkfI5CIUzSlUqeZu4REZ3A==,type:float]
            #ENC[AES256_GCM,data:VGG7Wy89mj4fSOEQal7lHyOKcxE=,iv:JWMQ+btru6kKk+1LcWrnlsvbvuCgQRDQMeaqS+k0mUs=,tag:us/Ad2lbRAxL5W6z+8puPQ==,type:comment]
            open_distance: ENC[AES256_GCM,data:+BlwCA==,iv:Tx3OWj+i3ZObU0l13Eu6P6mVwdPTHWmITtQKP3QxlsM=,tag:l7sHHYIcW1Y/MS/E/PHf0g==,type:float]
      opener:
        type: ENC[AES256_GCM,data:Erx6qU0a6L/xgqa/Tw==,iv:e0a7kZNvsPSW4IKrq53YPj5fco1gSiImUX33pGAjeao=,tag:nyQwZ/qNGShc6pfNMZqqJw==,type:str]
        settings:
            connection:
                host: ENC[AES256_GCM,data:7z37FSbQK/53dUKP,iv:kBB4KWzstExZCgDMceJ8CaTfiVNMf+D9Ku62Bh4pYaU=,tag:pUXRA0epG1w4oSoRBFmV9g==,type:str]
                port: ENC[AES256_GCM,data:Bqo=,iv:RVquO4kG5aLucwN9AMP/zCNQob6+Xb1DOGJpEhdq/kw=,tag:h6QG8fpz3h8yyhGOVDEEAQ==,type:int]
                api_key: ENC[AES256_GCM,data:vqaR7ScVpgwAWWl3SgNtbbF45MNVOTksSiMucRx8T9YkrYk0VnG73j3mX7hMbI+B8DnDGYJXd8NsIhljSpLs8t3iA4TgyRYDP2mNdkcynvOyVI3tXp0nLPwDZkZCgpdSF+xJZ78XIHrFhIXFiz24WfGkSybXlcCdRyqCc158NSsuz+ifBvzmxiEjGPbroo+7DBtxplod9ZJ5wqbYDh6MY1Pq76TqwWRwmXmN/Vg7yzwbVi7bjrTq,iv:Sm9azCaTwyZXCULqiAfl9oSt+ovmY52ylozbARwE+SU=,tag:xVyHCDXrVJPV68RbqyNoRw==,type:str]
                use_tls: ENC[AES256_GCM,data:BuvAwkI=,iv:bhsIQm+hnveNmHg+vHglU77CzOy6I2aJhHSTw2PtpzA=,tag:7wUG9dQ0OgC+oqSoWICr0w==,type:bool]
            entity_id: ENC[AES256_GCM,data:P0R6D5aV3uF7Oe2qUfUc2QSm3H0BbotnIUCnLOH70snP/OCLf+5SumWl,iv:nauJzIeDG3WqLdruNfJI4IHFRoBjx8lbHww5k43MJS8=,tag:bh5ZEyrtWn4S0Nxt4m57LQ==,type:str]
            enable_status_checks: ENC[AES256_GCM,data:C7K0jw==,iv:JdUlANrh12vntrsLy2v6jug0LpswTNMXGCJxZvgWWpw=,tag:/ZOb9Z+zKgYmbre9kI38cw==,type:bool]
      trackers:
        - id: ENC[AES256_GCM,data:yg==,iv:TGJlkMqBFvIi+VlU7pF6rckwUl3FgTZVGdNzEEW9cgo=,tag:zlsMGaRtXvtIYCxUbPNdbw==,type:int]
          lat_topic: ENC[AES256_GCM,data:wY4qKdTnonOnAga2MgdOfumDTKy4Xes2UA==,iv:YBUP80DOs2uNpNHrWt+tilZSN9RSpNKNkqBag91Wy/s=,tag:QeNugGf0wpji9T4/qYOVxw==,type:str]
          lng_topic: ENC[AES256_GCM,data:bUlX5TEMfWPn8hpxgGPs0XC0h0RPwwyY2vI=,iv:oMRqZyS++flvUJhU9dzNsyRxifrriDjeduk/vsWvYhY=,tag:raVySbvmU4HiTumGKxlySQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/deft-epigram-262002/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2024-02-17T19:04:18Z"
          enc: CiQAXK0pKh+2bRdzg4qGtRwouk1ZpQtdJ2u/DVsGk76+vlOeLYISSQAZIbLB5J8G6sxljjL95Sji286qVUEo+SN4rO9SPtKazo2qObyA+YG7Szff7Ks8l5YcUfedCY77j3zediPNpY89JhsgpatejTQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-09-11T12:22:14Z"
    mac: ENC[AES256_GCM,data:wHvzbyezvrryeC+PZh/oNf2GWvVgwHe4Hu5VnBaep435Ew2Kp1BpvuwFFgb3cz1a9D7zUozzCOeCJSCwxZsGOsLUvHPkIl3F2ARVahcRP07QYs5DNlLzwmfnmV7O89LHxFnWHigsbOYnjQEK9IOfzo6KqL0XtIsfV0dlg3QEWYg=,iv:IZ62tF+SAmQYyh4+0fzqG/zgZIdInxHbD2LVhVpxEgE=,tag:LvAhHmz4i5nv1wx5o25ylQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
