---
apiVersion: v1
kind: Service
metadata:
  name: grafana 
  labels:
    app.kubernetes.io/name: grafana
spec:
  type: LoadBalancer
  ports:
    - port: 4001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: grafana 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana 
  labels:
    app.kubernetes.io/name: grafana 
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana 
    spec:
      containers:
        - name: grafana 
          image: teslamate/grafana:1.19.2
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_USER
              value: "teslamate"
            - name: DATABASE_PASS
              value: "teslamate"
            - name: DATABASE_NAME
              value: "teslamate"
            - name: DATABASE_HOST
              value: "postgresql"
            - name: DATABASE_PORT
              value: "5432"
            - name: TZ
              value: "UTC"
            - name: LOCALE
              value: "en"
          ports:
            - name: http
              containerPort: 3000 
              protocol: TCP

