---
apiVersion: v1
kind: Service
metadata:
  name: grafana 
  labels:
    app.kubernetes.io/name: grafana
spec:
  ports:
    - port: 4001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: grafana 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana 
  labels:
    app.kubernetes.io/name: grafana 
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana 
    spec:
      containers:
        - name: grafana 
          image: teslamate/grafana
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_SERVER_DOMAIN
              value: "teslamate.bender.sway.org"
            - name: GF_SERVER_ROOT_URL
              value: "https://teslamate.bender.sway.org/grafana"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_SERVER_ROUTER_LOGGING
              value: "false"
            - name: DATABASE_USER
              value: "teslamate"
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgresql-password
            - name: DATABASE_NAME
              value: "teslamate"
            - name: DATABASE_HOST
              value: "postgresql"
            - name: DATABASE_PORT
              value: "5432"
            - name: TZ
              value: "UTC"
            - name: LOCALE
              value: "en"
          ports:
            - name: http
              containerPort: 3000 
              protocol: TCP

