images:
- name: teslamate/teslamate
  newTag: 3.0.0
- name: teslamate/grafana
  newTag: 3.0.0
- name: brchri/tesla-geogdo
  newTag: 2.3.1
- name: postgres
  newTag: 18.4-alpine@sha256:96d56f7f57c6aacd1fcb908bc83b345ec5f83231ee486dd66a1baadce274db88
- name: thomseddon/traefik-forward-auth
  newTag: 2.2.0
- name: mozilla/sops
  newTag: v3.7.3-alpine
- name: google/cloud-sdk
  newTag: 568.0.0-alpine

namespace: teslamate 

resources:
- teslamate.yaml 
- postgresql18.yaml
- grafana.yaml
- whoami.yaml
- auth.yaml
- ingress.yaml
- backup.yaml
- gdo.yaml

generators:
- traefik-forward-auth.yaml
- secrets.yaml
- gcpServiceUser.yaml
- gdo-config.yaml
