images:
- name: teslamate/teslamate
  newTag: 4.0.1
- name: teslamate/grafana
  newTag: 4.0.1
- name: brchri/tesla-geogdo
  newTag: 2.3.1
- name: postgres
  newTag: 18.6-alpine@sha256:432b3b824c0769275ec9b0947736ef8b376d6997bcaa9de29818f613819c2feb
- name: thomseddon/traefik-forward-auth
  newTag: 2.2.0
- name: mozilla/sops
  newTag: v3.7.3-alpine
- name: google/cloud-sdk
  newTag: 580.0.0-alpine

namespace: teslamate 

resources:
- teslamate.yaml 
- postgresql18.yaml
- grafana.yaml
- whoami.yaml
- auth.yaml
- ingress.yaml
- backup.yaml
- gdo.yaml

generators:
- traefik-forward-auth.yaml
- secrets.yaml
- gcpServiceUser.yaml
- gdo-config.yaml
