images:
- name: teslamate/teslamate
  newTag: 4.0.1
- name: teslamate/grafana
  newTag: 4.0.1
- name: brchri/tesla-geogdo
  newTag: 2.3.1
- name: postgres
  newTag: 18.4-alpine@sha256:1b1689b20d16a014a3d195653381cf2caa75a41a92d93b255a9d6ea29fd353aa
- name: thomseddon/traefik-forward-auth
  newTag: 2.2.0
- name: mozilla/sops
  newTag: v3.7.3-alpine
- name: google/cloud-sdk
  newTag: 573.0.0-alpine

namespace: teslamate 

resources:
- teslamate.yaml 
- postgresql18.yaml
- grafana.yaml
- whoami.yaml
- auth.yaml
- ingress.yaml
- backup.yaml
- gdo.yaml

generators:
- traefik-forward-auth.yaml
- secrets.yaml
- gcpServiceUser.yaml
- gdo-config.yaml
