---
apiVersion: v1
kind: Service
metadata:
  name: teslamate
  labels:
    app.kubernetes.io/name: teslamate
spec:
  ports:
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: teslamate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslamate
  labels:
    app.kubernetes.io/name: teslamate
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: teslamate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: teslamate
    spec:
      containers:
        - name: teslamate
          image: teslamate/teslamate:1.19.4
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_USER
              value: "teslamate"
            - name: DATABASE_PASS
              value: "teslamate"
            - name: DATABASE_NAME
              value: "teslamate"
            - name: DATABASE_HOST
              value: postgresql
            - name: MQTT_HOST
              value: 192.168.1.51
            - name: MQTT_USERNAME
              value: 
            - name: MQTT_PASSWORD
              value: 
            - name: MQTT_TLS
              value: "false"
            - name: MQTT_TLS_ACCEPT_INVALID_CERTS
              value: "false"
            - name: TZ
              value: "UTC"
            - name: LOCALE
              value: "en"
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP

